#服务的名称
spring:
  application:
    name: zuul-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 8001

#自定义路由映射
zuul:
  routes:
    service-consumer: /apigateway/consumer/**
    service-provider: /apigateway/provider/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  #忽略整个服务，对外提供接口
  ignored-services: order-service